# Configuration related to nickname, username etc. the things you see if you
# /whois pinobot
nickname = "Pinobot"
username = "pino"
realname = "Pino"

# Network configuration; i.e. where should Pinobot connect
host = "irc.libera.chat"
port = 6697
use_tls = true
