# Configuration related to nickname, username etc. the things you see if you
# /whois pinobot
nickname = "Pinobot"
username = "pino"
realname = "Pino"
hostname = "pinomachine"

# Network configuration; i.e. where should Pinobot connect
host = "irc.libera.chat"
port = 6669

# Behavior configuration.

# command_prefix: what's the letter you use to trigger pinobot.
# E.g. someone saying on channel the line "@v?jackal" <- the @ is the command prefix
command_prefix = "@"
